config/routes.rb
Rails.application.routes.draw do
  root to: "homes#show"
  resources :users, only: [:new, :create] do
    resources :password_resets, only: [:edit, :update]
  end
  resources :password_resets, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  
  resources :tweets, only: [:index]

  resources :users do
    resources :tweets, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/password_reset.rb
class PasswordReset < ActiveRecord::Base
  belongs_to :user
  before_create :generate_unique_token
  delegate :email, to: :user, allow_nil: true

  def to_param
    token
  end

  private

  def generate_unique_token
    self.token = generate_token
    while PasswordReset.exists?(token: self.token)
      self.token = generate_token
    end
  end

  def generate_token
    SecureRandom.hex(20).encode('UTF-8')
  end
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  validates :user, presence: true
  validates :body, presence: true, length: { maximum: 280 }
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true

  has_many :password_resets
  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Oath::ControllerHelpers
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def show
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create, :edit, :update], raise: false

  def new
    @password_reset = PasswordReset.new
  end

  def create
    user = User.find_by(email: params[:password_reset][:email])
    if user
      password_reset = PasswordReset.create(user: user)
      PasswordResetMailer.change_password(password_reset).deliver_now # NOTE: You'll want to delay this
    end
  end

  def edit
    @password_reset = PasswordReset.find_by!(token: params[:id], user_id: params[:user_id])
    @user = @password_reset.user
  end

  def update
    @password_reset = PasswordReset.find_by!(token: params[:id], user_id: params[:user_id])
    @user = @password_reset.user

    reset_password(@user, params[:password_reset][:password])

    if @user.save
      sign_in @user
      redirect_to root_path
    else
      render :edit
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create], raise: false

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to root_path
    else
      flash.notice = t('sessions.failure_after_create')
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = current_user.tweets.new(tweet_params)
  end

  private
  def tweet_params
    params.require(:tweet).permit(:user_id).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create], raise: false

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};analytics.SNIPPET_VERSION="4.0.0";
    analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    analytics.page();
    }}();
  </script>
<% end %>

app/views/application/_css_overrides.html.erb
<% if Rails.env.test? %>
  <style type="text/css">
    * {
      transition-property: none !important;
    }
  </style>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
  %>
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
 <% if signed_in? %>
    <%= current_user.email %> |
    <%= link_to t('sessions.sign_out'), session_path, method: :delete %>
  <% else %>
    <%= link_to t('sessions.sign_in'), new_session_path %> |
    <%= link_to t('users.sign_up'), new_user_path %>
  <% end %>
  <%= render "flashes" -%>
  <%= yield %>
  <%= render "javascript" %>
  <%= render "css_overrides" %>
</body>
</html>

app/views/password_resets/create.html.erb
<div class="password-reset">
  <p><%= t('password_resets.create.confirmation') %></p>
</div>

app/views/password_resets/edit.html.erb
<div class="password-reset">
  <h2><%= t('password_resets.edit.header') %></h2>

  <p><%= t('password_resets.edit.instructions') %></p>

  <%= form_for [@user, @password_reset] do |form| %>
    <div class="password-field">
      <%= form.label :password %>
      <%= form.password_field :password, require: true %>
    </div>

    <div class="submit-field">
      <%= form.submit t('password_resets.edit.submit') %>
    </div>
  <% end %>
</div>

app/views/password_resets/new.html.erb
<div class="password-reset">
  <h2><%= t('password_resets.new.header') %></h2>

  <p><%= t('password_resets.new.instructions') %></p>

  <%= form_for @password_reset do |form| %>
    <div class="text-field">
      <%= form.label :email %>
      <%= form.email_field :email, require: true %>
    </div>

    <div class="submit-field">
      <%= form.submit t('password_resets.new.submit') %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<%= form_for @user do |form| %>

  <% if @user.errors.any? %>
    <%= pluralize(@user.errors.count, "error") %> <%= t('users.sign_up_errors') %>
    <ul>
      <% @user.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email, require: true %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password, require: true %>
  </div>
  <div>
    <%= form.submit t('users.sign_up') %>
  </div>
<% end %>